# OpenJDK 17 기반 이미지 사용
FROM openjdk:17-jdk-alpine

# 타임존 설정
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# curl 설치
RUN apk add --no-cache curl

# 작업 디렉토리 설정
WORKDIR /app

# JAR 파일을 컨테이너로 복사
COPY deploy-practice.jar /app

# 실행 명령어
ENTRYPOINT ["java", "-jar", "deploy-practice.jar"]

# 포트포워딩
EXPOSE 8080