# Nginx 공식 이미지 사용
FROM nginx:latest

# 기존 기본 설정 제거
RUN rm -f /etc/nginx/conf.d/default.conf

# 빌드 컨텍스트에 있는 default-webroot-plugin.conf 파일 복사
COPY default-webroot-plugin.conf /etc/nginx/conf.d/default.conf

# 컨테이너가 사용하는 포트 노출
EXPOSE 80 443