# OpenJDK 17 기반 이미지 사용
FROM openjdk:17-jdk-alpine

# 작업 디렉토리 설정
WORKDIR /app

# JAR 파일을 컨테이너로 복사
COPY deploy-practice.jar /app

# 실행 명령어
ENTRYPOINT ["java", "-jar", "deploy-practice.jar"]

# 포트포워딩
EXPOSE 8080